Add time window to vary delay between actions
stanvanrooy/instauto pull request #131
Opened 2020-12-29 23:34 UTC by tibotix

Add delay_tolerance_delta attribute to set random time window when to perform the next action

2020-12-30 23:44 UTC, stanvanrooy commented
will check this tomorrow. Thanks for the contribution

2020-12-31 04:16 UTC, tibotix commented
No problem. I have also changed one line in the ``helpers.get_following` function as there were two inconsistent calls to first `client.following_get` and second `client.followers_get` , which should be probably `client.following_get` too. 
Don't know if this was intended but feels a bit wrong.
Sry for my inexperience, i wanted to open another pull requests for this request but now its in this too...

2020-12-31 16:01 UTC, stanvanrooy commented on instauto/bot/bot.py
> +    def __init__(self, user_name: str, password: str, delay_between_action: float = 2.0, delay_tolerance_delta: float = 0.0) -> None:
could you rename to `delay_variance`? Seems a bit more clear.

2020-12-31 16:04 UTC, stanvanrooy requested changes

2020-12-31 16:04 UTC, stanvanrooy commented on instauto/bot/bot.py
> +    def __init__(self, user_name: str, password: str, delay_between_action: float = 2.0, delay_tolerance_delta: float = 0.0) -> None:
could you rename to delay_variance? Seems a bit more clear.

2020-12-31 16:04 UTC, stanvanrooy commented on instauto/bot/bot.py
> +            delay_tolerance_delta: the amount of seconds to tolerance variing of the delay_between_action (to bring more randomness)
"the amount of variance to add to the delay. Delay will be random number between (delay - variance) - (delay + variance).

2020-12-31 16:04 UTC, stanvanrooy commented on instauto/helpers/friendships.py
> +        obj, result = client.following_get(obj)
Good catch!

2020-12-31 17:51 UTC, tibotix commented
Okay, all done. Sorry for my bad English..

2020-12-31 19:50 UTC, merged

2020-12-31 19:51 UTC, stanvanrooy commented
@all-contributors please add @tibotix for code